CREATE TABLE IF NOT EXISTS checked_log (_id INTEGER PRIMARY KEY, is_done INTEGER, unit_price INTEGER)
CREATE TABLE IF NOT EXISTS withdrawal_log(_id INTEGER PRIMARY KEY AUTOINCREMENT, w_date INTEGER, w_time INTEGER, amount INTEGER)
